services:
  db:
    build:
      context: .
      target: server
    ports:
      - "9600:9600"
    environment:
      SLATE_ADDR: 0.0.0.0:9600

  api:
    build:
      context: .
      target: api
    ports:
      - "9601:9601"
    depends_on:
      - db
    environment:
      SLATE_TCP_ADDR: db:9600
      SLATE_API_ADDR: 0.0.0.0:9601
      SLATE_POOL_SIZE: "4"
