services:
  db:
    build:
      context: ..
      dockerfile: dev/Dockerfile
      target: server
    ports:
      - "9600:9600"
    environment:
      SLATE_ADDR: 0.0.0.0:9600

  init:
    build:
      context: ..
      dockerfile: dev/Dockerfile
      target: server-init
    depends_on:
      - db
    environment:
      SLATE_SERVER_ADDR: db:9600
      SLATE_INIT_CONFIG: /etc/slate/collections.json
    volumes:
      - ./collections.json:/etc/slate/collections.json:ro

  collection-http:
    build:
      context: ..
      dockerfile: dev/Dockerfile
      target: collection-http
    ports:
      - "8080:8080"
    depends_on:
      init:
        condition: service_completed_successfully
    environment:
      SLATE_SERVER_ADDR: db:9600
      SLATE_COLLECTION: accounts
      SLATE_POOL_SIZE: "4"
