[package]
name = "slate-serde-bench"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "slate-serde-bench"
path = "src/main.rs"

[dependencies]
rmp-serde = "1"
bson = "2"
bincode = "1"
serde = { version = "1", features = ["derive"] }
