[package]
name = "slate-db"
version = "0.1.0"
edition = "2024"

[dependencies]
slate-store = { path = "../slate-store" }
slate-query = { path = "../slate-query" }
serde = { version = "1", features = ["derive"] }
bincode = "1"
bson = "2"

[dev-dependencies]
tempfile = "3"
bson = "2"
