[package]
name = "slate-db"
version = "0.1.0"
edition = "2024"

[features]
default = ["rocksdb"]
rocksdb = ["slate-store/rocksdb"]

[dependencies]
slate-store = { path = "../slate-store", default-features = false }
slate-query = { path = "../slate-query" }
serde = { version = "1", features = ["derive"] }
bson = "2"
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
tempfile = "3"
bson = "2"
