[package]
name = "slate-store"
version = "0.1.0"
edition = "2024"

[features]
default = ["rocksdb"]
rocksdb = ["dep:rocksdb"]

[dependencies]
rocksdb = { version = "0.22", optional = true }

[dev-dependencies]
tempfile = "3"
